BROKER_CATALOG = [
    {
        "id": "kiwoom",
        "name": "키움증권",
        "status": "ready",
        "required_fields": ["environment", "account_number", "app_key", "app_secret", "allowed_ip"],
        "optional_fields": ["account_password"],
    },
    {
        "id": "kis",
        "name": "한국투자증권",
        "status": "ready",
        "required_fields": ["environment", "account_prefix", "account_product_code", "app_key", "app_secret"],
        "optional_fields": ["hts_id"],
    },
    {
        "id": "db",
        "name": "DB증권",
        "status": "ready",
        "required_fields": ["environment", "account_number", "app_key", "app_secret"],
        "optional_fields": ["account_password"],
    },
    {
        "id": "ls",
        "name": "LS증권",
        "status": "ready",
        "required_fields": ["environment", "account_number", "app_key", "app_secret"],
        "optional_fields": ["account_password"],
    },
    {
        "id": "kb",
        "name": "KB증권",
        "status": "partner",
        "required_fields": [],
        "optional_fields": [],
    },
    {
        "id": "nh",
        "name": "NH투자증권",
        "status": "limited",
        "required_fields": [],
        "optional_fields": [],
    },
    {
        "id": "toss",
        "name": "토스 / 토스증권",
        "status": "unavailable",
        "required_fields": [],
        "optional_fields": [],
    },
    {
        "id": "kakaopay",
        "name": "카카오페이 / 카카오페이증권",
        "status": "unavailable",
        "required_fields": [],
        "optional_fields": [],
    },
    {
        "id": "naverpay",
        "name": "네이버페이",
        "status": "unavailable",
        "required_fields": [],
        "optional_fields": [],
    },
]
